spring:
  datasource:
    url: jdbc:mysql://3.35.27.189:3306/thecommercedb
    username: thecommerceuser
    password: look$up*
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        one-indexed-parameters: true
logging.level:
  org.hibernate.SQL: debug